import './globals.css'
import { Navbar } from '@/features/landing-page/Navbar'
import { HeroVid } from '@/features/landing-page/HeroVid'
import { Main } from '@/features/landing-page/Main'
import { HeroContent } from '@/features/landing-page/HeroContent'
import { Footer } from '@/features/landing-page/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#000912]
      flex
      flex-col
      items-center
      justify-center'>
        {children}
        <Navbar />
        <HeroVid />
        <Main />
        <HeroContent />
        <Footer />
      </body>
    </html>
  )
}
